# -*- coding: utf-8 -*-
"""Control_data_multisources

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VD7jbQI6XpRHUktBsh_vpzIHm7NCtOTf
"""

import pandas as pd

def charger_fichier_excel(nom_fichier):
    """Charge un fichier Excel et renvoie son contenu sous forme de DataFrame."""
    return pd.read_excel(nom_fichier)

def comparer_fichiers(fichier1, fichier2, fichier_export):
    """Compare deux fichiers Excel ligne par ligne et colonne par colonne et exporte les différences."""
    # Charger les deux fichiers
    df1 = charger_fichier_excel(fichier1)
    df2 = charger_fichier_excel(fichier2)

    # Afficher les dimensions des fichiers pour comprendre la différence
    print(f"Dimensions du fichier 1 (Lignes, Colonnes): {df1.shape}")
    print(f"Dimensions du fichier 2 (Lignes, Colonnes): {df2.shape}")

    # Afficher les premières lignes des fichiers pour inspection
    print("\nPremières lignes du fichier 1 :")
    print(df1.head())
    print("\nPremières lignes du fichier 2 :")
    print(df2.head())

    # Vérifier que les deux DataFrames ont la même forme
    if df1.shape != df2.shape:
        print("\nLes fichiers n'ont pas la même forme (différence de lignes ou de colonnes).")
        return

    # Comparer les DataFrames cellule par cellule et collecter les différences
    differences = []
    for i in range(df1.shape[0]):  # Parcourir les lignes
        for j in range(df1.shape[1]):  # Parcourir les colonnes
            if df1.iloc[i, j] != df2.iloc[i, j]:
                differences.append({
                    'Ligne': i + 1,  # +1 car les indices sont basés sur 0, mais pour l'utilisateur, les lignes commencent à 1
                    'Colonne': j + 1,  # +1 pour le même raisonnement
                    'Valeur Fichier 1': df1.iloc[i, j],
                    'Valeur Fichier 2': df2.iloc[i, j]
                })

    # Si des différences ont été trouvées, les exporter dans un fichier Excel
    if differences:
        df_differences = pd.DataFrame(differences)  # Créer un DataFrame à partir des différences
        df_differences.to_excel(fichier_export, index=False)  # Exporter dans un fichier Excel
        print(f"Les différences ont été exportées vers : {fichier_export}")
    else:
        print("Les fichiers sont identiques, aucune différence à exporter.")

# Exemple d'utilisation :
fichier1 = '/content/Export marchés PROD 17032025.xlsx'  # Nom du fichier téléchargé
fichier2 = '/content/Export marchés POC 17032025.xlsx'  # Nom du fichier téléchargé
fichier_export = 'differences.xlsx'  # Nom du fichier où les différences seront enregistrées

comparer_fichiers(fichier1, fichier2, fichier_export)

import os

# Vérifie si le fichier 'differences.xlsx' existe dans l'environnement
if os.path.exists('differences.xlsx'):
    print("Le fichier existe et est prêt à être téléchargé.")
else:
    print("Le fichier n'existe pas. Il peut ne pas avoir été créé.")

from google.colab import files

# Télécharger le fichier exporté
files.download('differences.xlsx')