# -*- coding: utf-8 -*-
"""Contrôle_data_saisie

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sLOciAu5uHNqlRScLsDw3MCpobnjAL1Z
"""

#Importations et fonctions de validation.

import pandas as pd
import re
from dateutil.parser import parse

def is_valid_date(value):
    try:
        if pd.isnull(value) or str(value).strip() == '':
            return True
        parse(str(value), dayfirst=True, fuzzy=False)
        return True
    except:
        return False

def is_valid_financial(value):
    try:
        if pd.isnull(value) or str(value).strip() == '':
            return True
        float(str(value).replace("€", "").replace(",", ".").replace(" ", ""))
        return True
    except:
        return False

def is_valid_siret(value):
    v = str(value).strip()
    if v == '' or pd.isnull(value):
        return True
    return v.isdigit() and len(v) == 14

#Analyse ciblée des colonnes selon la structure.

def analyze_excel_adapted(file_path):
    df = pd.read_excel(file_path, dtype=str)

    colonnes_date = [
        "Date de réception de la demande actuelle DC4",
        "Date envoi mail statut dossier non recevable\n(Respect process SGP)",
        "Date du traitement de la demande par le pôle administratif / Innoha",
        "Date identique pour demande de précisions au fournisseur et demande avis GFI",
        "Date limite initiale de réception de précisions ",
        "Date prévisionnelle recalée de remise des précisions du fournisseur",
        "Date de retour de l'avis du GFI",
        "Date envoi du rejet du DC4",
        "Date Pré-validation par mail/Validé par mail",
        "Date de validation",
        "Date limite avant la tacite notification (vision FRNS)",
        "Date de notification",
        "Date prévisionnelle d'achèvement des prestations sous-traitées"
    ]

    colonnes_siret = [
        "N° SIRET associé",
        "Numéro SIRET",
        "Numéro SIRET ",
    ]

    colonnes_financieres = [
        "Montant HT DC4"
    ]

    colonnes_texte = [col for col in df.columns if col not in colonnes_date + colonnes_siret + colonnes_financieres]

    results = {
        'dates_invalid': 0,
        'dates_invalid_lines': set(),
        'financial_invalid': 0,
        'financial_invalid_lines': set(),
        'siret_invalid': 0,
        'siret_invalid_lines': set(),
        'text_possible_issues': 0,
        'text_possible_issues_lines': set()
    }

    # Vérification dates
    for col in colonnes_date:
        if col in df.columns:
            for idx, val in df[col].items():
                if pd.isnull(val) or str(val).strip() == '':
                    continue
                if not is_valid_date(val):
                    results['dates_invalid'] += 1
                    results['dates_invalid_lines'].add(idx)

    # Vérification financières
    for col in colonnes_financieres:
        if col in df.columns:
            for idx, val in df[col].items():
                if pd.isnull(val) or str(val).strip() == '':
                    continue
                if not is_valid_financial(val):
                    results['financial_invalid'] += 1
                    results['financial_invalid_lines'].add(idx)

    # Vérification SIRET
    for col in colonnes_siret:
        if col in df.columns:
            for idx, val in df[col].items():
                if pd.isnull(val) or str(val).strip() == '':
                    continue
                if not is_valid_siret(val):
                    results['siret_invalid'] += 1
                    results['siret_invalid_lines'].add(idx)

    # Vérification texte (toutes les autres colonnes)
    for col in colonnes_texte:
        for idx, val in df[col].items():
            if pd.isnull(val) or str(val).strip() == '':
                continue
            if re.search(r'[^a-zA-Z0-9À-ÿ\s\-\.,]', str(val)):
                results['text_possible_issues'] += 1
                results['text_possible_issues_lines'].add(idx)

    # Convertir sets en listes triées pour un affichage clair
    for key in results.keys():
        if isinstance(results[key], set):
            results[key] = sorted(results[key])

    return results

#Utilisation du script et affichage des résultats

if __name__ == "__main__":
    fichier = "250627_TDB_DC4_V15.xlsx"
    anomalies = analyze_excel_adapted(fichier)

    print("\nRésumé des anomalies détectées (avec lignes concernées) :")
    for k, v in anomalies.items():
        if 'lines' in k:
            print(f"{k} (lignes) : {v}")
        else:
            print(f"{k} (nombre) : {v}")

from google.colab import files
import pandas as pd

# 1. Upload du fichier Excel
uploaded = files.upload()

# 2. Récupérer le nom du fichier uploadé
filename = list(uploaded.keys())[0]

# 3. Lire l'onglet 'TDB DC4' en prenant la 2ème ligne comme header (header=1)
df = pd.read_excel(filename, sheet_name='TDB DC4', header=1)

# 4. Nettoyer les noms de colonnes (enlever espaces superflus)
df.columns = df.columns.str.strip()

# 5. Récupérer le nom de la colonne A (index 0)
col_a = df.columns[0]
print(f"Colonne A détectée dans l'onglet 'TDB DC4' : '{col_a}'")

# 6. Supprimer les lignes où la colonne A est vide ou NaN
df_clean = df[df[col_a].notna() & (df[col_a] != '')]

# 7. Détecter les doublons dans cette colonne (sans compter les vides)
doublons = df_clean[df_clean.duplicated(subset=[col_a], keep=False)]

# 8. Afficher uniquement le nombre de lignes en doublon
print(f"Nombre de lignes en doublon dans la colonne '{col_a}' (hors vides) : {len(doublons)}")