# -*- coding: utf-8 -*-
"""Automation_mail

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YD0Hc9GjQKOGh8etAfMu8pSTUFERiM6q
"""

from google.colab import files
import pandas as pd
import io

def upload_and_detect_na():
    """Upload et détection des valeurs manquantes"""
    uploaded = files.upload()
    if not uploaded:
        print("Aucun fichier uploadé !")
        return None

    file_name = next(iter(uploaded))
    df = pd.read_excel(io.BytesIO(uploaded[file_name]))
    na_rows = df[df.isna().any(axis=1)]

    if not na_rows.empty:
        print(f" {len(na_rows)} ligne(s) avec NA détectées")
        return na_rows
    else:
        print("Aucun NA trouvé")
        return None

# Exécution
print("Veuillez uploader votre fichier Excel :")
na_data = upload_and_detect_na()

def create_na_report(na_data):
    """Crée un fichier Excel avec les NA"""
    if na_data is not None:
        output_filename = "NA_Report.xlsx"
        na_data.to_excel(output_filename, index=False)
        print(f"Fichier {output_filename} créé")
        return output_filename
    return None

# Exécution
report_file = create_na_report(na_data)

import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email import encoders
import os

def send_na_report(email_recipient, attachment_path):
    """Envoie le rapport par email"""
    if not attachment_path:
        print("Aucun fichier à envoyer")
        return

    # Configuration (à personnaliser)
    email_sender = "oudam.d.pich@gmail.com"
    email_password = "vlax dcoi dtmq bjyl"  # Mot de passe d'application

    # Préparation email
    msg = MIMEMultipart()
    msg['From'] = email_sender
    msg['To'] = email_recipient
    msg['Subject'] = "Rapport des valeurs manquantes"

    body = "Veuillez trouver ci-joint le rapport des valeurs manquantes."
    msg.attach(MIMEText(body, 'plain'))

    # Pièce jointe
    with open(attachment_path, 'rb') as attachment:
        part = MIMEBase('application', 'octet-stream')
        part.set_payload(attachment.read())
    encoders.encode_base64(part)
    part.add_header('Content-Disposition', f'attachment; filename="{attachment_path}"')
    msg.attach(part)

    # Envoi
    try:
        with smtplib.SMTP('smtp.gmail.com', 587) as server:
            server.starttls()
            server.login(email_sender, email_password)
            server.send_message(msg)
        print("Email envoyé avec succès à", email_recipient)
    except Exception as e:
        print(f"Erreur d'envoi : {e}")
    finally:
        os.remove(attachment_path)
        print("Fichier temporaire supprimé")

# Exécution (remplacez l'email du destinataire)
if report_file:
    send_na_report("oudam.d.pich@gmail.com", report_file)
